library/Zend/Db/Select.php, tests/Zend/Db/Select/StaticTest.php
This essentially is a recursive regex to ensure balanced parentheses.
Partially fixes regressions from #418 including #424, but not SQL subqueries.
=> Loosen regex to allow nested function calls in SQL

library/Zend/Json/Server.php, tests/Zend/Json/ServerTest.php
Fixes Issue #475.
Zend_Server_Exception should include the method name for easier debugging since it is not captured in the stack trace
=> Fixes #475 - Enhance Zend_Server_Exception message

library/Zend/Validate/EmailAddress.php, tests/Zend/Validate/EmailAddressTest.php
Fixes #62
The problem is that IDN domain cannot be converted to `xn--` in PHP 5.2 (there are some PHP libraries, that implement it, but we can't include them in ZF). So this is rather a "progressive enhacement" for PHP 5.3+ (with intl enabled)
cc @froschdesign
=> Zend_Validate_EmailAddress: IDN domains are converted to punnycode if possible

library/Zend/Cache/Core.php
=> Allow overriding cache id and tag validation in Zend_Cache

library/Zend/Navigation/Container.php
To improved code-completion in IDEs like PHPStorm
=> Added more specific return documentation for Zend_Navigation Pages

library/Zend/Translate.php, library/Zend/Translate/Adapter.php
The parameters between [brackets] are optional
=> [Zend_Translate] Extend PHPDocumentation to cover 'magic' behavior

puppet/manifests/default.pp, puppet/scripts/php-build.sh
=> Installs PHPUnit via apt-get instead of via PEAR.

library/Zend/Controller/Request/HttpTestCase.php
Adds patch to the list of valid method types array.
=> Fix for #511 - Add PATCH to the list of allowed methods in Zend_Controller_Request_HttpTestCase

.travis.yml
Ref #518 
This PR prevents Travis PHP 7 builds from failing because of missing memcache(d) extensions
=> Use different php.ini config for PHP 7 Travis builds

library/Zend/Controller/Action/Helper/ViewRenderer.php, tests/Zend/Controller/Action/Helper/ViewRendererTest.php
ping @akrabat 
Please take a closer look to this fix. Thanks!
=> Extend view renderer controller fix (#440)

library/Zend/Amf/Server.php, library/Zend/XmlRpc/Server.php
> The func_get_arg() and func_get_args() functions will no longer return the
>  original value that was passed to a parameter and will instead provide the
> current value (which might have been modified).
(from https://github.com/php/php-src/blob/master/UPGRADING)
See http://3v4l.org/HvCqN for example of changed behaviour
=> Fix PHP 7 BC breaks in Zend_XmlRpc/Amf_Server

library/Zend/Serializer/Adapter/PythonPickle.php, tests/Zend/DateTest.php, tests/Zend/Log/Writer/AbstractTest.php, tests/Zend/Log/Writer/DbTest.php, tests/Zend/Serializer/Adapter/PhpCodeTest.php, tests/Zend/Service/DeveloperGarden/OfflineSecurityTokenServerTest.php
This one together with #540 should get us closer to "green" build on PHP7.
See the distinct commits for details about each fix.
=> Fixed errors in tests on PHP7

tests/php52_config.ini, tests/php52_install_dependencies.sh
Something probably changed in the TravisCI images or in the pecl, so I think it is OK not to run memcache(d) tests against PHP 5.2.
Closes #543 
cc @akrabat @froschdesign
=> TravisCI: Skip memcache(d) on PHP 5.2

library/Zend/Application.php, tests/Zend/Application/ApplicationTest.php
Needed to prevent warnings when the (default) Bootstrap object is set, which will trigger a load of ZendX_Application_Resource_FrontController, as described in https://github.com/zendframework/zf1/issues/564
=> Allow early suppressing of file not found warnings in Zend_Application

library/Zend/Http/Client.php, tests/Zend/Cloud/Infrastructure/Adapter/Ec2Test.php, tests/Zend/Cloud/Infrastructure/Adapter/RackspaceTest.php, tests/Zend/Gdata/App/EntryTest.php, tests/Zend/Gdata/AppTest.php, tests/Zend/Gdata/AuthSubTest.php, tests/Zend/Http/Client/StaticTest.php, tests/Zend/Http/CookieJarTest.php, tests/Zend/Service/Audioscrobbler/AudioscrobblerTest.php, tests/Zend/Service/Flickr/OfflineTest.php
With the ZF2015-04 patch in 1.12.12, we were no longer allowing non-string, non-stringable objects as header values. This broke a number of other classes, however, which required integer and/or float values (e.g., to set a Content-Length header).  This patch casts those types to strings before attempting to set them as header values.
=> Cast int and float to string when creating headers

library/Zend/Db/Select.php, tests/Zend/Db/Select/StaticTest.php
Fixed for unbalanced parentheses and deeply nested functions
=> Fix regexp to detect functions in column definition

library/Zend/Xml/Security.php, tests/Zend/Xml/MultibyteTest.php, tests/Zend/Xml/TestAsset/Security.php
There is an anonymous function which is not supported on PHP 5.2 https://github.com/zendframework/zf1/blob/master/library/Zend/Xml/Security.php#L192
(the Travis is failing)
cc @weierophinney
=> ZF2015-06 fix broke the ZF on PHP 5.2

library/Zend/Http/Response.php, tests/Zend/Http/ResponseTest.php, tests/Zend/Http/_files/response_587, tests/Zend/Http/_files/response_587_empty, tests/Zend/Http/_files/response_587_null
In Version 1.12.13 is a bug which is not in Version 1.12.11.
If an HTTP header value is empty I get the Exception "Invalid header line detected" in Zend_Http_Response line 573
This happens because the regex in line 528 does not match if the value is empty.
As far as I know empty values are allowed in HTTP 1.1.
If I change the regex in line 528 from
"|^([\w-]+):\s*(.+)|s"
to
"|^([\w-]+):\s*(.*)|s"
it works fine. So just replacing the + by a *.
It would be nice if this could be fixed in the code, because this breaks existing code.
For me it broke the feed reader, which is fetching and parsing an RSS feed where one HTTP response header value is empty.
=> "Invalid header line detected" error if HTTP header value is empty

library/Zend/Dom/Query.php, tests/Zend/Dom/QueryTest.php, tests/phpunit.xml
A new document type has been added to Zend_Dom_Query, it's called 'Dom' and means that the document setter received a DOMDocument instance instead of a string. Therefor the getter will also return the instance. In the queryXpath method there will be no additional parsing will be done.
I needed this to give the LIBXML_PARSEHUGE option to loadHTML() and recognize that it would've been a way to implement these options as a third information on the query class (much like encoding). But i'd found it to be complicating the whole scenario. Also i like to work with objects so injecting a DOMDocument should be totally fine.
=> Fixes #504 - Cannot parse huge documents in Zend_Dom_Query

tests/Zend/Db/Adapter/Pdo/TestCommon.php
This PR fixes the test issue with null byte for Zend_Db_Adapter_Pdo.
=> Fixed the null byte test for Zend_Db_Adapter_Pdo

tests/Zend/Crypt/MathTest.php
This should make the Zend_Crypt_MathTest run on PHP 5.2/5.3
ping @weierophinney
=> ZF2015-09: The Zend_Crypt_MathTest should run on PHP 5.2/5.3

tests/Zend/Soap/AllTests.php
I think it is better to have tests green, so the proper attention will be paid to any failures.
Closes #650
=> Skip Zend_Soap tests on Travis with PHP 5.4.37 because of segfaults

library/Zend/Db/Adapter/Pdo/Abstract.php, library/Zend/Db/Adapter/Pdo/Mssql.php, library/Zend/Db/Adapter/Pdo/Sqlite.php, tests/Zend/Db/Adapter/Pdo/MssqlTest.php, tests/Zend/Db/Adapter/Pdo/MysqlTest.php, tests/Zend/Db/Adapter/Pdo/SqliteTest.php
This PR fixes the #655 issue for MySQL. I removed the filter of null-bytes from quote() in Pdo\Abstract and I moved in MsSQL and Sqlite for [ZF2015-08](http://framework.zend.com/security/advisory/ZF2015-08). This should remove the double quotes of null-bytes for MySQL. I provided [this test](https://github.com/ezimuel/zf1/blob/fix/655/tests/Zend/Db/Adapter/Pdo/MysqlTest.php#L322-L327) for MySQL. 
Waiting feedback from @Thomas-Gelf, @moshevds and others.
=> Fix for 655 issue
